main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sidona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('register/', include(('t1_register.urls', 't1_register'), namespace='t1_register')),
    path('login/', include(('t1_login.urls', 't1_login'), namespace='t1_login')),
    path('myprofile/', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
    path('wishlist_donasi/', include(('t4_wishlist_donasi.urls', 't4_wishlist_donasi'), namespace='t4_wishlist_donasi')),
    path('donasi/', include(('t4_donasi.urls', 't4_donasi'), namespace='t4_donasi')),
    path('penggalangan_dana_3/', include(('t3_penggalangan_dana.urls', 't3_penggalangan_dana'), namespace='t3_penggalangan_dana')),
    path('catatan_pengajuan/', include('t3_catatan_pengajuan.urls')),
    path('kategori_pd/', include('t3_kategori_penggalangan_dana.urls')),
    path('data_penggalang_dana/', include('t5_data_penggalang_dana.urls')),
    path('riwayat_penggunaan_dana/', include('t5_riwayat_penggunaan_dana.urls')),
    path('penggalangan_dana/', include(('penggalangan_dana.urls', 'penggalangan_danas'), namespace='penggalangan_dana')),
    path('daftar_pengguna/', include('daftar_pengguna.urls')),
]

t4_donasi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.donasi_view, name='index'),
    path('detail/<str:id_donasi>', views.donasi_detail_view, name='detail_donasi'),
    path('form/<str:id_donasi>', views.donasi_add_view, name='form_donasi'),
]
app_name = 't4_donasi'

t4_wishlist_donasi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.wishlist_view, name='index'),
    path('detail/<str:id_donasi>/', views.wishlist_detail_view, name='wishlist_detail'),
    path('delete/<str:id_donasi>/', views.wishlist_delete_view, name='wishlist_delete'),
    path('add/<str:id_donasi>/', views.wishlist_add_view, name='wishlist_add'),
]
app_name = 't4_wishlist_donasi'

t4_wishlist_donasi/models.py
from django.db import models

# Create your models here.

t4_wishlist_donasi/views.py
import json
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.db import connection
from collections import namedtuple


def index(request):
    return render(request, 'wishlist_donasi.html', {})


def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]


def wishlist_view(request):
   if request.session.has_key('email'):
        cursor = connection.cursor()
        myresult = {}
        hasil = []
        data = []
        try:
            email = request.session['email'][0]
            cursor.execute("SET SEARCH_PATH TO sidona")
            cursor.execute(
                "select pd.id, pd.judul, k.nama_kategori from penggalangan_dana_pd pd join kategori_pd k on k.id = pd.id_kategori where pd.id in (select wd.idPD from wishlist_donasi wd where wd.email = '" + email + "');"
            )
            hasil = namedtuplefetchall(cursor)
            cursor.execute(
                "select * from individu where email = '" + email + "';"
            )
            data = namedtuplefetchall(cursor)
            myresult = {
                "result" : [
                    {
                        "name" : "hasil",
                        "list" : hasil,
                    },
                    {
                        "name" : "data",
                        "list" : data,
                    }
                ]
            }
        except Exception as e:
            print(e)
        finally:
            cursor.close()
        return render(request, 'wishlist_donasi.html', myresult)
   else:
        return HttpResponseRedirect('/login/masuk')


def wishlist_detail_view(request, id_donasi):
    idPD = id_donasi
    if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        try:
            email = request.session['email'][0]
            cursor.execute("SET SEARCH_PATH TO sidona")
            cursor.execute(
                "select pd.id idPD, judul, kota, provinsi, tanggal_aktif_awal, tanggal_aktif_akhir, sisa_hari, jumlah_dibutuhkan, jumlah_terkumpul, jumlah_terpakai, nama_kategori from penggalangan_dana_pd pd join kategori_pd k on pd.id_kategori = k.id where pd.id = '" + idPD + "';"
            )
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)
        finally:
            cursor.close()
        return render(request, 'wishlist_donasi_detail.html', {"result" : result})
    else:
        return HttpResponseRedirect('/login/masuk')


def wishlist_delete_view(request, id_donasi):
    idPD = id_donasi
    if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        try:
            email = request.session['email'][0]
            print(email)
            cursor.execute("SET SEARCH_PATH TO sidona")
            cursor.execute(
                "delete from wishlist_donasi where email = '" + email + "' and idpd = '" + idPD + "';"
            )
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)
        finally:
            cursor.close()
        return HttpResponseRedirect('/wishlist_donasi')
    else:
        return HttpResponseRedirect('/login/masuk')


def wishlist_add_view(request, id_donasi):
    idPD = id_donasi
    print(idPD)

    if request.session.has_key('email'):
        print("MASUK GAISKU")
        cursor = connection.cursor()
        result = []
        try:
            email = request.session['email'][0]
            print(email)
            cursor.execute("SET SEARCH_PATH TO sidona")
            cursor.execute(
                "insert into wishlist_donasi values ('" + email + "', '" + idPD + "');"
            )
            result = namedtuplefetchall(cursor)
            print(result)
        except Exception as e:
            print(e)
        finally:
            cursor.close()
        return HttpResponseRedirect('/wishlist_donasi')
    else:
        print('GAMASUK GAIS')
        return HttpResponseRedirect('/login/masuk')

t4_wishlist_donasi/templates/wishlist_donasi.html
<!-- adopted from https://tailwindcomponents.com/component/responsive-table-5 -->

{% extends "base_loggedin.html" %}
{% load static %}


{% block title %}Sidona - Wishlist Donasi{% endblock %}


{% block body_block %}
<h1 class="text-xl md:text-2xl lg:text-3xl font-semibold pt-8 pb-2 text-center">List Wishlist Donasi</h1>
<section class="container mx-auto p-6 font-mono">
    <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
      <div class="w-full overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="text-md font-semibold tracking-wide text-left text-white bg-gray-500 uppercase border-b border-gray-600">
                <th class="px-4 py-3">ID</th>
                <th class="px-4 py-3">Judul</th>
                <th class="px-4 py-3">Kategori</th>
                <th class="px-4 py-3">Action</th>
            </tr>
          </thead>

          <tbody class="bg-white">

            {% for rest in result %}

              {% if rest.name == 'hasil' %}
                  {% for res in rest.list %}
                    <tr class="text-gray-700">
                      <td class="px-4 py-3 border">
                        <div class="flex items-center text-sm">
                          <div>
                            <p class="font-semibold text-black">{{ res.id }}</p>
                          </div>
                        </div>
                      </td>
                      <td class="px-4 py-3 text-ms font-semibold border">{{ res.judul }}</td>
                      <td class="px-4 py-3 text-xs border">
                        <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm"> {{ res.nama_kategori }} </span>
                      </td>
                      <td class="px-4 py-3 border">
                        <div class="flex items-center text-sm">
                          <div>
                            <p><a href="{% url 't4_wishlist_donasi:wishlist_detail' id_donasi=res.id %}" id="buttonku" class="text-purple-500 font-semibold cursor:pointer" style="box-shadow:inset 0 -0.1666666667em 0 0 #fff, inset 0 -0.3333333333em 0 0 #C4B5FD" style="cursor: pointer;">detail</a></p>
                            <p><a href="{% url 't4_donasi:form_donasi' id_donasi=res.id %}" id="buttonku" class="text-purple-500 font-semibold cursor:pointer" style="box-shadow:inset 0 -0.1666666667em 0 0 #fff, inset 0 -0.3333333333em 0 0 #C4B5FD" style="cursor: pointer;">donasi</a></p>
                            <p><a href="{% url 't4_wishlist_donasi:wishlist_delete' id_donasi=res.id %}" id="buttonku" class="text-purple-500 font-semibold cursor:pointer" style="box-shadow:inset 0 -0.1666666667em 0 0 #fff, inset 0 -0.3333333333em 0 0 #C4B5FD" style="cursor: pointer;">delete</a></p>
                          </div>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}


              {% elif rest.name == 'data' %}
                  {% for res in rest.list %}
                    <div class="font-bold text-l mb-2 mt-4">Jumlah Wishlist Donasi: {{ res.jumlah_wishlist }}</div>
                  {% endfor %}
              {% endif %}



            {% endfor %}

          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock %}

t4_wishlist_donasi/templates/wishlist_donasi_detail.html
<!-- adopted from https://tailwindcomponents.com/component/responsive-table-5 -->

{% extends "base_loggedin.html" %}
{% load static %}


{% block title %}Sidona - Wishlist Donasi{% endblock %}


{% block body_block %}

{% for res in result %}
    <h1 class="text-xl md:text-2xl lg:text-3xl font-semibold pt-8 pb-2 text-center">Detail Penggalangan Dana</h1>
    <div class="register bg-white container mx-auto border-box lg:w-2/5 md:w-4/5 p-8 mt-2 rounded-2xl shadow-md">
        <form class="w-full max-w-sm">
            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-full-name">
                    ID
                </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.idpd }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Judul
                </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.judul }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Kota
                </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.kota }}
                    </label>
                </div>
            </div>


            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Provinsi
                </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.provinsi }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Tanggal Aktif Awal
                    </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.tanggal_aktif_awal }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Tanggal Aktif Akhir
                    </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.tanggal_aktif_akhir }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Jumlah Dibutuhkan
                    </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.jumlah_dibutuhkan }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Jumlah Terkumpul
                    </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.jumlah_terkumpul }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Jumlah Terpakai
                    </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.jumlah_terpakai }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Sisa Hari
                    </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.sisa_hari }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Kategori
                    </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.nama_kategori }}
                    </label>
                </div>
            </div>
        </form>
        <a href="{% url 't4_wishlist_donasi:index' %}" class="py-2 px-2 font-medium text-white rounded bg-red-300 transition duration-300">Back</a>
    </div>
{% endfor %}

{% endblock %}