main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sidona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('register/', include(('t1_register.urls', 't1_register'), namespace='t1_register')),
    path('login/', include(('t1_login.urls', 't1_login'), namespace='t1_login')),
    path('myprofile/', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
    path('wishlist_donasi/', include(('t4_wishlist_donasi.urls', 't4_wishlist_donasi'), namespace='t4_wishlist_donasi')),
    path('donasi/', include(('t4_donasi.urls', 't4_donasi'), namespace='t4_donasi')),
    path('penggalangan_dana_3/', include(('t3_penggalangan_dana.urls', 't3_penggalangan_dana'), namespace='t3_penggalangan_dana')),
    path('catatan_pengajuan/', include('t3_catatan_pengajuan.urls')),
    path('kategori_pd/', include('t3_kategori_penggalangan_dana.urls')),
    path('data_penggalang_dana/', include('t5_data_penggalang_dana.urls')),
    path('riwayat_penggunaan_dana/', include('t5_riwayat_penggunaan_dana.urls')),
    path('penggalangan_dana/', include(('penggalangan_dana.urls', 'penggalangan_danas'), namespace='penggalangan_dana')),
    path('daftar_pengguna/', include('daftar_pengguna.urls')),
]

t4_donasi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.donasi_view, name='index'),
    path('detail/<str:id_donasi>', views.donasi_detail_view, name='detail_donasi'),
    path('form/<str:id_donasi>', views.donasi_add_view, name='form_donasi'),
]
app_name = 't4_donasi'

t4_donasi/models.py
from django.db import models

# Create your models here.

t4_donasi/views.py
import json
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from datetime import datetime


def index(request):
    return render(request, 'list_donasi.html', {})

def detail_donasi(request):
    return render(request, 'detail_donasi.html', {})

def form_donasi(request):
    return render(request, 'form_donasi.html', {})


def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]


def donasi_view(request):
   if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        try:
            email = request.session['email'][0]
            print(email)
            cursor.execute("SET SEARCH_PATH TO sidona")
            cursor.execute(
                "select pd.id as idpd, pd.judul, k.nama_kategori, s.status from donasi d join penggalangan_dana_pd pd on pd.id = d.idpd join kategori_pd k on k.id = pd.id_kategori join status_pembayaran s on s.id = d.idstatuspembayaran where email='" + email + "';"
            )
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)
        finally:
            cursor.close()
        return render(request, 'list_donasi.html', {"result" : result})
   else:
        return HttpResponseRedirect('/login/masuk')


def donasi_detail_view(request, id_donasi):
    idPD = id_donasi
    if request.session.has_key('email'):
        cursor = connection.cursor()
        result = []
        try:
            email = request.session['email'][0]
            cursor.execute("SET SEARCH_PATH TO sidona")
            cursor.execute(
                "select * from donasi d join penggalangan_dana_pd pd on d.idpd = pd.id where d.idpd = '" + idPD + "' and d.email = '" + email + "';"
            )
            result = namedtuplefetchall(cursor)
        except Exception as e:
            print(e)
        finally:
            cursor.close()
        return render(request, 'detail_donasi.html', {"result" : result})
    else:
        return HttpResponseRedirect('/login/masuk')


def donasi_add_view(request, id_donasi):
    print(id_donasi)
    if request.session.has_key('email'):
        result = []
        if request.method == 'POST':
            print("MASUK GAISKU")
            email = request.session['email'][0]
            print(email)
            idPD = id_donasi
            print(id_donasi)
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            print(timestamp)
            nominal = request.POST.get('nominal')
            print(nominal)
            metode = request.POST.get('metode_bayar')
            print(metode)
            status = request.POST.get('status_anonim')
            print(status)
            doa = request.POST.get('doa')
            print(doa)
            cursor = connection.cursor()
            result = []
            try:
                cursor.execute("SET SEARCH_PATH TO sidona")
                cursor.execute(
                    "insert into donasi values ('" + email + "', '" + timestamp + "', '" + nominal + "', '" + metode +  "', '" + status + "', '" + doa + "', '" + idPD + "', '924491011');"
                )
                result = namedtuplefetchall(cursor)
                print(result)
            except Exception as e:
                print(e)
            finally:
                cursor.close()
        return render(request, 'form_donasi.html', {"result" : result})
    else:
        print('GAMASUK GAIS')
        return HttpResponseRedirect('/login/masuk')

t4_donasi/templates/detail_donasi.html
<!-- adopted from https://tailwindcomponents.com/component/responsive-table-5 -->

{% extends "base_loggedin.html" %}
{% load static %}


{% block title %}Sidona - Detail Donasi{% endblock %}


{% block body_block %}

{% for res in result %}
    <h1 class="text-xl md:text-2xl lg:text-3xl font-semibold pt-8 pb-2 text-center">Detail Donasi</h1>
    <div class="register bg-white container mx-auto border-box lg:w-2/5 md:w-4/5 p-8 mt-2 rounded-2xl shadow-md">
        <form class="w-full max-w-sm">
          <div class="md:flex md:items-center mb-6">
            <div class="md:w-2/3">
            <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                Email
            </label>
            </div>
            <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                    {{ res.email }}
                </label>
            </div>
          </div>

            <div class="md:flex md:items-center mb-6">
                <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                    Timestamp
                </label>
                </div>
                <div class="md:w-2/3">
                    <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                        {{ res.timestamp }}
                    </label>
                </div>
            </div>

            <div class="md:flex md:items-center mb-6">
              <div class="md:w-2/3">
              <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                  Judul
              </label>
              </div>
              <div class="md:w-2/3">
                  <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                      {{ res.judul }}
                  </label>
              </div>
          </div>

          <div class="md:flex md:items-center mb-6">
            <div class="md:w-2/3">
            <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                Nominal
            </label>
            </div>
            <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                    {{ res.nominal }}
                </label>
            </div>
          </div>

          <div class="md:flex md:items-center mb-6">
            <div class="md:w-2/3">
            <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                Metode Bayar
            </label>
            </div>
            <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                    {{ res.metodebayar }}
                </label>
            </div>
          </div>

          <div class="md:flex md:items-center mb-6">
            <div class="md:w-2/3">
            <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                Status Anonim
            </label>
            </div>
            <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                    {{ res.statusanonim }}
                </label>
            </div>
          </div>

          <div class="md:flex md:items-center mb-6">
            <div class="md:w-2/3">
            <label class="block text-gray-500 font-bold mb-1 md:mb-0 pr-4" for="inline-password">
                Doa
            </label>
            </div>
            <div class="md:w-2/3">
                <label class="block text-gray-500 font-bold md:text-left mb-1 md:mb-0 pr-4" for="inline-full-name">
                    {{ res.doa }}
                </label>
            </div>
          </div>

        </form>
        <a href="{% url 't4_donasi:index' %}" class="py-2 px-2 font-medium text-white rounded bg-red-300 transition duration-300">Back</a>
    </div>
{% endfor %}

{% endblock %}

t4_donasi/templates/form_donasi.html
<!-- adopted from https://tailwindcomponents.com/component/responsive-table-5 -->

{% extends "base_loggedin.html" %}
{% load static %}


{% block title %}Sidona - Form Donasi{% endblock %}


{% block body_block %}
<h1 class="text-xl md:text-2xl lg:text-3xl font-semibold pt-8 pb-2 text-center">Buat Donasi</h1>
<div class="register bg-white container mx-auto border-box lg:w-2/5 md:w-4/5 p-8 mt-2 rounded-2xl shadow-md">
    <form class="w-full max-w-sm" method="POST">
      {% csrf_token %}
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
              <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Email Donatur
              </label>
            </div>
            <div class="md:w-2/3">
              <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" name="email" type="text" value="otomatis terisi" disabled>
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
              <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                Timestamp
              </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-full-name" type="text" value="otomatis terisi" disabled>
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
              <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                  Judul Penggalangan Dana
                </label>
              </div>
              <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-full-name" type="text" value= "otomatis terisi" disabled>
              </div>
        </div>

        <div class="md:flex md:items-center mb-6">
              <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                  Nominal (Rupiah)
                </label>
              </div>
              <div class="md:w-2/3">
                <input class="bg-gray-50 appearance-none border-2 border-gray-50 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" name="nominal" type="text" placeholder="Masukkan nominal">
              </div>
        </div>

        <div class="md:flex md:items-center mb-6">
              <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                  Metode Bayar
                </label>
              </div>
              <div class="md:w-2/3">
                <div class="relative">
                    <select name="metode_bayar" class="block appearance-none w-full bg-gray-50 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">
                      <option> DonaPay </option>
                      <option> Transfer </option>
                    </select>
                    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                      <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                    </div>
                </div>
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
              <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                  Status Anonim
                </label>
              </div>
              <div class="md:w-2/3">
                <div class="relative">
                    <select name="status_anonim" class="block appearance-none w-full bg-gray-50 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">
                      <option> Anonim </option>
                      <option> Non-anonim </option>
                    </select>
                    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                      <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                    </div>
                </div>
              </div>
        </div>

        <div class="md:flex md:items-center mb-6">
              <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                  Doa
                </label>
              </div>
              <div class="md:w-2/3">
                <input class="bg-gray-50 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" name="doa" type="text" placeholder="Masukkan doa">
              </div>
        </div>
        <div class="md:flex md:items-center">
          <div class="md:w-1/3"></div>
          <div class="md:w-2/3">
              <input type="submit" name="" value="Submit" class="shadow bg-red-300 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" onclick="">
          </div>
      </div>
    </form>
</div>
{% endblock %}

t4_donasi/templates/list_donasi.html
<!-- adopted from https://tailwindcomponents.com/component/responsive-table-5 -->

{% extends "base_loggedin.html" %}
{% load static %}


{% block title %}Sidona - List Donasi{% endblock %}


{% block body_block %}
<h1 class="text-xl md:text-2xl lg:text-3xl font-semibold pt-8 pb-2 text-center">List Donasi</h1>
<section class="container mx-auto p-6 font-mono">
    <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
      <div class="w-full overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="text-md font-semibold tracking-wide text-left text-white bg-gray-500 uppercase border-b border-gray-600">
                <th class="px-4 py-3">ID</th>
                <th class="px-4 py-3">Judul</th>
                <th class="px-4 py-3">Kategori</th>
                <th class="px-4 py-3">Status Pembayaran</th>
                <th class="px-4 py-3">Action</th>
            </tr>
          </thead>

          <tbody class="bg-white">

            {% for res in result %}
                <tr class="text-gray-700">
                  <td class="px-4 py-3 border">
                    <div class="flex items-center text-sm">
                      <div>
                        <p class="font-semibold text-black">{{ res.idpd }}</p>
                      </div>
                    </div>
                  </td>
                  <td class="px-4 py-3 text-ms font-semibold border">{{ res.judul }}</td>
                  <td class="px-4 py-3 text-xs border">
                    <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm">{{ res.nama_kategori }}</span>
                  </td>  
                  <td class="px-4 py-3 text-xs border">
                    <span class="px-2 py-1 font-semibold leading-tight text-gray-700 bg-gray-100 rounded-sm">{{ res.status }}</span>
                  </td>
                  <td class="px-4 py-3 border">
                    <div class="flex items-center text-sm">
                      <div>
                        <p><a href="{% url 't4_donasi:detail_donasi' id_donasi=res.idpd %}" id="buttonku" class="text-purple-500 font-semibold cursor:pointer" style="box-shadow:inset 0 -0.1666666667em 0 0 #fff, inset 0 -0.3333333333em 0 0 #C4B5FD" style="cursor: pointer;">detail</a></p>
                        
                        {% if res.status == 'menunggu pembayaran' %}
                          <p><a href="#" id="buttonku" class="text-purple-500 font-semibold cursor:pointer" style="box-shadow:inset 0 -0.1666666667em 0 0 #fff, inset 0 -0.3333333333em 0 0 #C4B5FD" style="cursor: pointer;">upload bukti</a></p>

                        {% elif res.status == 'pengecekan' %}
                          <p><a href="#" id="buttonku" class="text-purple-500 font-semibold cursor:pointer" style="box-shadow:inset 0 -0.1666666667em 0 0 #fff, inset 0 -0.3333333333em 0 0 #C4B5FD" style="cursor: pointer;">lihat bukti</a></p>
    
                        {% elif res.status == 'sukses' %}
                          <p><a href="#" id="buttonku" class="text-purple-500 font-semibold cursor:pointer" style="box-shadow:inset 0 -0.1666666667em 0 0 #fff, inset 0 -0.3333333333em 0 0 #C4B5FD" style="cursor: pointer;">lihat bukti</a></p>

                        {% endif %}
                      </div>
                    </div>
                  </td>
                </tr>
            {% endfor %}

          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock %}