main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sidona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('register/', include(('t1_register.urls', 't1_register'), namespace='t1_register')),
    path('login/', include(('t1_login.urls', 't1_login'), namespace='t1_login')),
    path('myprofile/', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
    path('wishlist_donasi/', include(('t4_wishlist_donasi.urls', 't4_wishlist_donasi'), namespace='t4_wishlist_donasi')),
    path('donasi/', include(('t4_donasi.urls', 't4_donasi'), namespace='t4_donasi')),
    path('penggalangan_dana_3/', include(('t3_penggalangan_dana.urls', 't3_penggalangan_dana'), namespace='t3_penggalangan_dana')),
    path('catatan_pengajuan/', include('t3_catatan_pengajuan.urls')),
    path('kategori_pd/', include('t3_kategori_penggalangan_dana.urls')),
    path('data_penggalang_dana/', include('t5_data_penggalang_dana.urls')),
    path('riwayat_penggunaan_dana/', include('t5_riwayat_penggunaan_dana.urls')),
    path('penggalangan_dana/', include(('penggalangan_dana.urls', 'penggalangan_danas'), namespace='penggalangan_dana')),
    path('daftar_pengguna/', include('daftar_pengguna.urls')),
]

t1_register/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', views.register_admin, name='register_admin'),
    path('individu/', views.register_individu, name='register_individu'),
    path('organisasi/', views.register_organisasi, name='register_organisasi'),
]
app_name = 't1_register'

t1_register/models.py
from django.db import models

# Create your models here.

t1_register/views.py
import json
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt


def index(request):
    return render(request, 'register.html', {})

def register_admin(request):
    return render(request, 'register_admin.html', {})

def register_individu(request):
    return render(request, 'register_individu.html', {})

def register_organisasi(request):
    return render(request, 'register_organisasi.html', {})



# from django.shortcuts import render, redirect
# from django.db import connection

# def authentication_success(request):
#     if "username" in request.session:
#         return render(request,'success.html')
#     else:
#         return redirect('/')

# def verified(data):
#     query = """
#     select * from penggalang_dana;
#     """
#     cursor = connection.cursor()
#     cursor.execute("set search_path to sidona;")
#     cursor.execute(query)

#     user_data = fetch(cursor)
#     for users in user_data:
#         username_status = data['email'] == users['email']
#         password_status = data['password'] == users['password']
#         if(username_status and password_status):
#             return True
#     return False

# def fetch(cursor):
#     columns = [col[0] for col in cursor.description]
#     return [dict(zip(columns, row)) for row in cursor.fetchall()]

# def is_email_taken(email):
#     cursor = connection.cursor()
#     cursor.execute("set search_path to sidona;")
#     cursor.execute("select email from penggalang_dana;")
#     all_registered_email = fetch(cursor)
#     result = False
#     for emails in all_registered_email:
#         if emails['email'] == email:
#             result = True
#             break
#     return result

# def is_admin(email_input):
#     # fetch semua nomor_pegawai dari admin
#     query1 = """
#     select email from admin;
#     """
#     cursor = connection.cursor()
#     cursor.execute("set search_path to sidona;")
#     cursor.execute(query1)

#     email_admin_response = fetch(cursor)
#     for email in email_admin_response:
#         if(email_input == email['email']):
#             return True
#     return False

# def unauthorized(request):
#     if "email" in request.session:
#         return render(request,'unauthorized.html')
#     else:
#         return redirect('/')

# def register(request):
#     if "email" in request.session:
#         return redirect('/')
#     return render(request,'register.html')

# def register_admin(request):
#     if "email" in request.session:
#         return redirect('/')
#     response={}
#     response['error'] = False
#     form = RegisterFormAdministrator(request.POST or None)
#     response['form'] = form
#     if(request.method == 'POST' and form.is_valid()):
#         email = request.POST['email']
#         password = request.POST['password']
#         nomor_identitas = request.POST['nomor_identitas']
#         nama_lengkap = request.POST['nama_lengkap']
#         tanggal_lahir = request.POST['tanggal_lahir']
#         email = request.POST['email']
#         alamat = request.POST['alamat']
#         if(not is_email_taken(email) and (not is_email_taken(email)) and (not is_id_taken(nomor_identitas))):
#             insert_pengguna(email,password,nomor_identitas,nama_lengkap,tanggal_lahir,email,alamat)
#             insert_administrator(email)
#             return redirect('/register/success')
#         else:
#             response['error'] = True
#     return render(request,'register_administrator.html',response)

# def insert_pengguna(username,password,nomor_identitas,nama_lengkap,tanggal_lahir,email,alamat):
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("INSERT INTO PENGGUNA (email,username,password,nama_lengkap,nomor_id,tanggal_lahir,alamat) values (%s,%s,%s,%s,%s,%s,%s)",[email,username,password,nama_lengkap,nomor_identitas,tanggal_lahir,alamat])

# def insert_administrator(username):
#     # kode rs defaults to RSHB2001
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("insert into administrator (nomor_pegawai,username,kode_rs) values(%s,%s,%s)",[get_new_nomor_pegawai(),username,'RSHB2001'])

# def insert_dokter(username,no_sip,spesialisasi):
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("insert into dokter (id_dokter,username,no_sip,spesialisasi) values(%s,%s,%s,%s)",[get_new_id_dokter(),username,no_sip,spesialisasi])

# def insert_pasien(username,nomor_rekam_medis):
#     # asuransi defaults to manulife
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("insert into pasien (no_rekam_medis,username,nama_asuransi) values(%s,%s,%s)",[nomor_rekam_medis,username,"Manulife"])

# def insert_alergi(nomor_rekam_medis,alergi):
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("insert into alergi_pasien (no_rekam_medis,alergi) values(%s,%s)",[nomor_rekam_medis,alergi])

# def register_dokter(request):
#     if "username" in request.session:
#         return redirect('/')
#     response={}
#     response['error'] = False
#     form = RegisterFormDokter(request.POST or None)
#     response['form'] = form
#     if(request.method == 'POST' and form.is_valid()):
#         print(request.POST)
#         username = request.POST['username']
#         password = request.POST['password']
#         nomor_identitas = request.POST['nomor_identitas']
#         nama_lengkap = request.POST['nama_lengkap']
#         tanggal_lahir = request.POST['tanggal_lahir']
#         email = request.POST['email']
#         alamat = request.POST['alamat']
#         nomor_sip = request.POST['nomor_sip']
#         spesialisasi = request.POST['spesialisasi']
#         if(not is_username_taken(username) and (not is_email_taken(email)) and (not is_id_taken(nomor_identitas))):
#             insert_pengguna(username,password,nomor_identitas,nama_lengkap,tanggal_lahir,email,alamat)
#             insert_dokter(username,nomor_sip,spesialisasi)
#             return redirect('/register/success')
#         else:
#             request['error'] = True
#     return render(request,'register_dokter.html',response)

# def register_pasien(request):
#     if "username" in request.session:
#         return redirect('/')
#     response={}
#     response['error'] = False
#     form = RegisterFormPasien(request.POST or None)
#     response['form'] = form
#     if(request.method == 'POST' and form.is_valid()):
#         print(request.POST)
#         username = request.POST['username']
#         password = request.POST['password']
#         nomor_identitas = request.POST['nomor_identitas']
#         nama_lengkap = request.POST['nama_lengkap']
#         tanggal_lahir = request.POST['tanggal_lahir']
#         email = request.POST['email']
#         alamat = request.POST['alamat']
#         alergi = request.POST['alergi']
#         nomor_rekam_medis = get_new_no_rekam_medis()
#         if(not is_username_taken(username) and (not is_email_taken(email)) and (not is_id_taken(nomor_identitas))):
#             insert_pengguna(username,password,nomor_identitas,nama_lengkap,tanggal_lahir,email,alamat)
#             insert_pasien(username,nomor_rekam_medis)
#             insert_alergi(nomor_rekam_medis,alergi)
#             return redirect('/register/success')
#         else:
#             response['error'] = True
#     return render(request,'register_pasien.html',response)


# def register_success(request):
#     return render(request,'register-success.html')

# def get_new_nomor_pegawai():
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("select nomor_pegawai from administrator;")
#     all_nomor_pegawai = fetch(cursor)
#     temp = []
#     for no_pegawai in all_nomor_pegawai:
#         temp.append(no_pegawai['nomor_pegawai'])
#     result = int(max(temp)) + 1
#     return result

# def get_new_id_dokter():
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("select id_dokter from dokter;")
#     all_id_dokter = fetch(cursor)
#     temp = []
#     for id_dokter in all_id_dokter:
#         temp.append(id_dokter['id_dokter'])
#     result = int(max(temp)) + 1
#     return result

# def get_new_no_rekam_medis():
#     cursor = connection.cursor()
#     cursor.execute("set search_path to medika_go;")
#     cursor.execute("select no_rekam_medis from pasien;")
#     all_no_rekam_medis = fetch(cursor)
#     temp = []
#     anynumber = False
#     result = ""
#     for no_rekam_medis in all_no_rekam_medis:
#         if no_rekam_medis['no_rekam_medis'].isnumeric():
#             anynumber = True
#             result = no_rekam_medis['no_rekam_medis']
#             temp.append(int(no_rekam_medis['no_rekam_medis']))
#     if(anynumber):
#         return int(max(temp)) + 1
#     else:
#         return 0

t1_register/templates/register.html
{% extends "base.html" %}
{% load static %}


{% block title %}Sidona - Daftar{% endblock %}


{% block body_block %}
  <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 gap-5">

    <!--Card 1-->
    <div class="rounded overflow-hidden shadow-lg">
      <div class="px-6 pt-4">
        <div class="font-bold text-xl mb-2">Daftar Sebagai Admin</div>
      </div>  
      <div class="px-6">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#admin</span>
      </div>
      <div class="px-6 py-4">
        <p class="text-gray-700 text-base">
          Daftar sebagai admin dan bantu operasional Sidona agar lebih baik untuk membantu sesama!
        </p>
      </div>
      <div class="px-6 py-4 mb-4">
        <a href="{% url 't1_register:register_admin' %}" class="py-2 px-2 font-medium text-white bg-red-300 rounded hover:bg-red-300 transition duration-300">Daftar Sebagai Admin</a>
      </div>
    </div>

    <!--Card 2-->
    <div class="rounded overflow-hidden shadow-lg">
      <div class="px-6 pt-4">
        <div class="font-bold text-xl mb-2">Daftar Sebagai Penggalang Dana</div>
      </div>  
      <div class="px-6">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#individu</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#organisasi</span>
      </div>
      <div class="px-6 py-4">
        <p class="text-gray-700 text-base">
          Daftar sebagai penggalang dana dan berikan kontribusi terbaikmu untuk saudara sekitar!
        </p>
      </div>
      <div class="px-6 py-4 mb-4">
        <a href="{% url 't1_register:register_individu' %}" class="py-2 px-2 font-medium text-white bg-red-300 rounded hover:bg-red-300 transition duration-300">Daftar Sebagai Individu</a>
        <a href="{% url 't1_register:register_organisasi' %}" class="py-2 px-2 font-medium text-white bg-red-300 rounded hover:bg-red-300 transition duration-300">Daftar Sebagai Organisasi</a>
      </div>
    </div>
</div>
{% endblock %}

t1_register/templates/register_admin.html
<!-- adopted from https://tailwindcomponents.com/component/responsive-table-5 -->

{% extends "base.html" %}
{% load static %}


{% block title %}Sidona - Signup Admin{% endblock %}


{% block body_block %}
<h1 class="text-xl md:text-2xl lg:text-3xl font-semibold pt-8 pb-2 text-center">Signup Form - Admin</h1>
<div class="register bg-white container mx-auto border-box lg:w-2/5 md:w-4/5 p-8 mt-2 rounded-2xl shadow-md">
    <form class="w-full max-w-sm">
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Email
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="mail@domain.com">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                Password
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-password" type="password" placeholder="******************">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Nama
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan nama">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                No HP
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan no HP">
            </div>
        </div>

        <div class="md:flex md:items-center">
            <div class="md:w-1/3"></div>
            <div class="md:w-2/3">
                <button class="shadow bg-red-300 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
                Signup
                </button>
            </div>
        </div>
    </form>
</div>    
{% endblock %}

t1_register/templates/register_individu.html
<!-- adopted from https://tailwindcomponents.com/component/responsive-table-5 -->

{% extends "base.html" %}
{% load static %}


{% block title %}Sidona - Signup Individu{% endblock %}


{% block body_block %}
<h1 class="text-xl md:text-2xl lg:text-3xl font-semibold pt-8 pb-2 text-center">Signup Form - Individu</h1>
<div class="register bg-white container mx-auto border-box lg:w-2/5 md:w-4/5 p-8 mt-2 rounded-2xl shadow-md">
    <form class="w-full max-w-sm">
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Email
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="mail@domain.com">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                Password
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-password" type="password" placeholder="******************">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Nama
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan nama">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                No HP
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan no HP">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Alamat
                </label>
            </div>
            <div class="md:w-2/3">
                <textarea class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan alamat" rows="3"></textarea>
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Nama Bank
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan nama bank">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                No Rekening
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan no rekening">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                NIK
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan NIK">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Tanggal Lahir
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan tanggal lahir">
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Jenis Kelamin
                </label>
            </div>
            <div class="md:w-2/3">
                <div class="relative">
                    <select class="block appearance-none w-full bg-gray-50 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">
                      <option> Laki-laki </option>
                      <option> Perempuan </option>
                    </select>
                    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                      <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                    </div>
                </div>    
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                Foto KTP
                </label>
            </div>
            <div class="md:w-2/3">
                <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-600" id="inline-full-name" type="text" placeholder="Masukkan foto rekening">
            </div>
        </div>

        <div class="md:flex md:items-center">
            <div class="md:w-1/3"></div>
            <div class="md:w-2/3">
                <button class="shadow bg-red-300 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
                Signup
                </button>
            </div>
        </div>
    </form>
</div>    
{% endblock %}

t1_register/templates/register_success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success Daftar</title>
</head>

<body>
    <h1>Berhasil Register</h1>
    <a href="/login">
        <button>
            Login
        </button>
    </a>
</body>

</html>

t1_register/templates/success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logged in</title>
</head>

<body>
    <h1>Successfully Logged In</h1>
    <h1>Redirecting you to your profile</h1>
</body>

<script type="text/javascript">
    setTimeout(function () {
        window.location.href = "/profile/"
    }, 2000);
</script>

</html>

t1_register/templates/unauthorized.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthorized</title>
</head>

<body>
    <h1>You are not authorized to view this page</h1>
    <a href="/">
        <button>
            Go Home
        </button>
    </a>
</body>

</html>