main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

myprofile/urls.py
from django.urls import path
from .views import *

app_name = 'myprofile'

urlpatterns = [
    path('', myprofile, name='myprofile'),
]

penggalangan_dana/urls.py
from django.urls import path
from .views import *

app_name = 'penggalangan_dana'

urlpatterns = [
    path('', penggalangan_dana, name='penggalangan-dana'),
    path('create_pd/', create_pd, name='create-pd'),
    path('see_pd/<id>/', see_pd, name='see-pd'),
    path('see_pd_detail/<id>/', see_pd_detail, name='see-pd-id'),
    path('see_all_pd/', see_all_pd, name='see-all-pd'),
    path('create_pd/form/', ended_form, name='ended-form'),
    path('create_pd/opsi/', before_initial_form, name='before-initial-form'),
    path('create_pd/in_form/', initial_form, name='initial-form'),
    path('create_pd/check_data/', check_data, name='check-data'),
    path('create_pd/check_data_2/', check_data_2, name='check-data-2'),
    path('kelola_penyakit/', kelola_penyakit, name='kelola-penyakit'),
    path('add_penyakit/', add_penyakit, name='add-penyakit'),
    path('update_penyakit/', update_penyakit, name='update-penyakit'),
]

sidona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('register/', include(('t1_register.urls', 't1_register'), namespace='t1_register')),
    path('login/', include(('t1_login.urls', 't1_login'), namespace='t1_login')),
    path('myprofile/', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
    path('wishlist_donasi/', include(('t4_wishlist_donasi.urls', 't4_wishlist_donasi'), namespace='t4_wishlist_donasi')),
    path('donasi/', include(('t4_donasi.urls', 't4_donasi'), namespace='t4_donasi')),
    path('penggalangan_dana_3/', include(('t3_penggalangan_dana.urls', 't3_penggalangan_dana'), namespace='t3_penggalangan_dana')),
    path('catatan_pengajuan/', include('t3_catatan_pengajuan.urls')),
    path('kategori_pd/', include('t3_kategori_penggalangan_dana.urls')),
    path('data_penggalang_dana/', include('t5_data_penggalang_dana.urls')),
    path('riwayat_penggunaan_dana/', include('t5_riwayat_penggunaan_dana.urls')),
    path('penggalangan_dana/', include(('penggalangan_dana.urls', 'penggalangan_danas'), namespace='penggalangan_dana')),
    path('daftar_pengguna/', include('daftar_pengguna.urls')),
]

t1_login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('masuk/', views.loggedInView, name='masuk'),
    path('logout/', views.logout, name='logout'),
]
app_name = 't1_login'

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>		
		{% block meta %} 
		<title>Sidona</title>
		{% endblock meta %}

		<link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"/>
		<link rel="stylesheet" href="./css/tailwind.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

		<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
		<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
		<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Roboto&display=swap" rel="stylesheet">

		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	</head>
	<body>
		<nav class="bg-gray-500 shadow-lg">
			<div class="max-w-6xl mx-auto px-4">
				<div class="flex justify-between">
					<div class="flex space-x-7">
						<!-- Website Logo -->
						<div>
							<a href="{% url 'main:home' %}" class="flex items-center py-4 px-2">
								<span class="font-semibold text-white text-lg">SIDONA</span>
							</a>
						</div>
						
						<!-- Primary Navbar items -->
						<div class="hidden md:flex items-center space-x-1">
							<a href="#" class="py-4 px-2 text-white hover:text-red-200 transition duration-300 ">Home</a>
							<a href="#" class="py-4 px-2 text-white hover:text-red-200 transition duration-300 ">About</a>
						</div>
					</div>

					<!-- Secondary Navbar items -->
					<div class="hidden md:flex items-center space-x-3 ">
						<a href="{% url 't1_login:index' %}" class="py-2 px-2 font-medium text-white rounded hover:bg-red-300 hover:text-white transition duration-300">Log In</a>
						<a href="{% url 't1_register:index' %}" class="py-2 px-2 font-medium text-white bg-red-300 rounded hover:bg-red-300 transition duration-300">Sign Up</a>
					</div>

					<!-- Mobile menu button -->
					<div class="md:hidden flex items-center">
						<button class="outline-none mobile-menu-button">
							<svg class=" w-6 h-6 text-gray-500 hover:text-red-300 "
								x-show="!showMenu"
								fill="none"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								viewBox="0 0 24 24"
								stroke="white"
							>
								<path d="M4 6h16M4 12h16M4 18h16"></path>
							</svg>
						</button>
					</div>
				</div>
			</div>

			<!-- mobile menu -->
			<div class="hidden mobile-menu">
				<ul class="">
					<li class="active"><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">Home</a></li>
					<li class="active"><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">About</a></li>
					<li><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">Login</a></li>
					<li><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">Signup</a></li>
				</ul>
			</div>
		</nav>
    {% block body_block %} {% endblock %}
	</body>
	<script>
		const btn = document.querySelector("button.mobile-menu-button");
		const menu = document.querySelector(".mobile-menu");

		btn.addEventListener("click", () => {
			menu.classList.toggle("hidden");
		});
	</script>
</html>

templates/base_loggedin.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>		
		{% block meta %} 
		<title>Sidona</title>
		{% endblock meta %}

		<link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"/>
		<link rel="stylesheet" href="./css/tailwind.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

		<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
		<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
		<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Roboto&display=swap" rel="stylesheet">

		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	</head>
	<body>
		<nav class="bg-gray-500 shadow-lg">
			<div class="max-w-6xl mx-auto px-4">
				<div class="flex justify-between">
					<div class="flex space-x-7">
						<!-- Website Logo -->
						<div>
							<a href="{% url 'main:home' %}" class="flex items-center py-4 px-2">
								<span class="font-semibold text-white text-lg">SIDONA</span>
							</a>
						</div>
						
						<!-- Primary Navbar items -->
						<div class="hidden md:flex items-center space-x-1">
							<a href="{% url 'myprofile:myprofile' %}" class="py-4 px-2 text-white hover:text-red-200 transition duration-300 ">My Profile</a>
							<a href="{% url 't3_penggalangan_dana:index' %}" class="py-4 px-2 text-white hover:text-red-200 transition duration-300 ">Penggalangan Dana</a>
							<a href="{% url 'penggalangan_dana:see-pd' %}" class="py-4 px-2 text-white hover:text-red-200 transition duration-300 ">My Penggalangan Dana</a>
							<a href="{% url 't4_wishlist_donasi:index' %}" class="py-4 px-2 text-white hover:text-red-200 transition duration-300 ">My Wishlist Donasi</a>
							<a href="{% url 't4_donasi:index' %}" class="py-4 px-2 text-white hover:text-red-200 transition duration-300 ">My Donasi</a>
						</div>
					</div>

					<!-- Secondary Navbar items -->
					<div class="hidden md:flex items-center space-x-3 ">
						<a href="{% url 't1_login:logout' %}" class="py-2 px-2 font-medium text-white bg-red-300 rounded hover:bg-red-300 transition duration-300">Log Out</a>
					</div>

					<!-- Mobile menu button -->
					<div class="md:hidden flex items-center">
						<button class="outline-none mobile-menu-button">
							<svg class=" w-6 h-6 text-gray-500 hover:text-red-300 "
								x-show="!showMenu"
								fill="none"
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								viewBox="0 0 24 24"
								stroke="white"
							>
								<path d="M4 6h16M4 12h16M4 18h16"></path>
							</svg>
						</button>
					</div>
				</div>
			</div>

			<!-- mobile menu -->
			<div class="hidden mobile-menu">
				<ul class="">
					<li class="active"><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">Home</a></li>
					<li class="active"><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">About</a></li>
					<li><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">Login</a></li>
					<li><a href="#" class="block text-sm text-white px-2 py-4 hover:bg-red-300 hover:text-white">Signup</a></li>
				</ul>
			</div>
		</nav>
    {% block body_block %} {% endblock %}
	</body>
	<script>
		const btn = document.querySelector("button.mobile-menu-button");
		const menu = document.querySelector(".mobile-menu");

		btn.addEventListener("click", () => {
			menu.classList.toggle("hidden");
		});
	</script>
</html>